In [2]:
import numpy as np

In [11]:
#numpy.reshape(arr, newshape, order')

np.arange(8).reshape(2,4)

arr=np.arange(8)

np.reshape(arr,(2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
#numpy.ndarray.flat
a=np.arange(8).reshape(2,4) 
for x in a.flat:
    print(x,end=" ")
    

0 1 2 3 4 5 6 7 

In [11]:
#ndarray.flatten(order)


#Return copy of original array
#If you modify any value of this array value of original array is not affected.

a = np.arange(8).reshape(2,4) 
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
#flattened one-dimensional array.
#numpy.ravel(a, order)

#Return only reference/view of original array
#If you modify the array you would notice that the value of original array also changes.


a = np.arange(8).reshape(2,4) 
a.ravel() 

array([0, 1, 2, 3, 4, 5, 6, 7])

In [16]:
#permutes the dimension of the given array.
#numpy.transpose(arr, axes)


a = np.arange(12).reshape(3,4) 
np.transpose(a)


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [18]:
#rolls the specified axis backwards, until it lies in a specified position
#numpy.rollaxis(arr, axis, start)

a = np.arange(8).reshape(2,2,2) 
print(a)
print("*"*20)
print(np.rollaxis(a,2)) 
print("*"*20)
print(np.rollaxis(a,2,1))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
********************
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]
********************
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]


In [21]:
#function interchanges the two axes of an array.
#numpy.swapaxes(arr, axis1, axis2)

a = np.arange(8).reshape(2,2,2) 
#now swap numbers between axis 0 (along depth) and axis 2 (along )
print(a)
np.swapaxes(a, 2, 0)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [22]:
x = np.array([[1], [2], [3]]) 
y = np.array([4, 5, 6])  
   
# tobroadcast x against y 
b = np.broadcast(x,y)  
# it has an iterator property, a tuple of iterators along self's "components." 

for a in b:
    print(a,end=" ")

(1, 4) (1, 5) (1, 6) (2, 4) (2, 5) (2, 6) (3, 4) (3, 5) (3, 6) 

In [23]:
#function broadcasts an array to a new shape. It returns a read-only view on the original array.
#numpy.broadcast_to(array, shape, subok)

a = np.arange(4).reshape(1,4) 
np.broadcast_to(a,(4,4))


array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [31]:
#function expands the array by inserting a new axis at the specified position
#numpy.expand_dims(arr, axis)

x = np.array(([1,2],[3,4])) 

#np.expand_dims(x, axis = 0)
np.expand_dims(x, axis = 1)

array([[[1, 2]],

       [[3, 4]]])

In [33]:
# function is used to join two or more arrays of the same shape along a specified axis.
#numpy.concatenate((a1, a2, ...), axis)

a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 
#np.concatenate((a,b))
#np.concatenate((a,b),axis = 1)               

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [39]:
# joins the sequence of arrays along a new axis

#Stack the two arrays along axis 0:
#np.stack((a,b),0)

#Stack the two arrays along axis 1
#np.stack((a,b),1)



array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [40]:
#Horizontal stacking:
np.hstack((a,b))


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [41]:
#Vertical stacking:
np.vstack((a,b)) 

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [43]:
# divides the array into subarrays along a specified axis
#numpy.split(ary, indices_or_sections, axis)

a = np.arange(9)

#Split the array in 3 equal-sized subarrays:
#np.split(a,3) 

#Split the array at positions indicated in 1-D array:
np.split(a,[4,6])

[array([0, 1, 2, 3]), array([4, 5]), array([6, 7, 8])]

In [56]:
#numpy.hsplit is a special case of split() function where axis is 1 indicating a horizontal split
a = np.arange(16).reshape(4,4) 
#Horizontal splitting:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [59]:
#Vertical splitting:
np.vsplit(a,2) 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [61]:
#returns a new array with the specified size.
#numpy.resize(arr, shape)

a = np.array([[1,2,3],[4,5,6]]) 

In [62]:
np.resize(a, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
#If the new size is greater than the original, the repeated copies of entries in the original are contained.
np.resize(a,(3,4)) 

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6]])

In [64]:
#adds values at the end of an input array.
#numpy.append(arr, values, axis)

a = np.array([[1,2,3],[4,5,6]]) 
#Append elements to array:
np.append(a, [7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
#Append elements along axis 0:
np.append(a, [[7,8,9]],axis = 0) 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
#Append elements along axis 1:
np.append(a, [[5,5,5],[7,8,5]],axis = 1)

array([[1, 2, 3, 5, 5, 5],
       [4, 5, 6, 7, 8, 5]])

In [70]:
#inserts values in the input array along the given axis and before the given index.
a = np.array([[1,2],[3,4],[5,6]]) 

#Axis parameter not passed. The input array is flattened before insertion.
#np.insert(a,3,[11,12])

In [72]:
#Broadcast along axis 0:
np.insert(a,1,[11,12],axis = 0) 

array([[ 1,  2],
       [11, 12],
       [ 3,  4],
       [ 5,  6]])

In [57]:
#Broadcast along axis 1:
np.insert(a,1,11,axis = 1)

array([[ 1, 11,  2],
       [ 3, 11,  4],
       [ 5, 11,  6]])

In [73]:
#numpy.delete(arr, obj, axis)

a = np.arange(12).reshape(3,4)

#Array flattened before delete operation as axis not used:
#np.delete(a,4)

In [60]:
#Column 2 deleted:
np.delete(a,1,axis = 1)

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11]])

In [61]:
#returns an array of unique elements
a = np.array([5,2,6,2,7,5,6,8,2,9])

np.unique(a) 

array([2, 5, 6, 7, 8, 9])

In [51]:
a=np.array([[2,3,4],[3,4]])




4
