In [ ]:
import numpy as np

In [ ]:
arr1=np.array([2,23,4,35,16])
#dtype,


In [ ]:
arr2=np.array(np.arange(1,20,2))
arr2

In [ ]:
arr2.dtype #describing the type of the elements in the array.
#arr2.shape #the dimensions of the array : For a matrix with n rows and m columns, shape will be (n,m). 
#arr2.size  #he total number of elements of the array
#arr2.itemsize #the size in bytes of each element of the array. same sa : => arr2.dtype.itemsize


In [22]:
arr3=np.array([12,4.7,34,56,7,"Amit",'Ram',23])

In [37]:
#2D array
arr4=np.array([(1,2,3),(4,5,6)])
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
#arr4.dtype
#arr4.shape
#arr4.size


6

In [52]:
arr5=np.arange(20).reshape(5,4)
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [55]:
#3D array

arr6=np.array([[[1,2,3],[4,5,6]],[[7,8,9,],[10,11,12]]])
arr6

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
arr6.shape

(2, 2, 3)

In [63]:
arr7=np.arange(18).reshape(2,3,3)
arr7

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [69]:
#np.zeros((3, 4))
#np.ones( (2,3,4), dtype=np.int16 ) 
#np.empty( (2,3) )  

In [74]:
np.arange(1,10,0.2) # it accepts float arguments   :any argument can be float 

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [76]:
a=np.array([2,3,4,5])
b=np.arange(4)

In [77]:
a+b

array([2, 4, 6, 8])

In [78]:
a*2

array([ 4,  6,  8, 10])

In [80]:
a<4

array([ True,  True, False, False])

In [83]:
x=np.array([(1,2,3),(4,5,6)])
y=np.array([(2,3,6),(1,3,4)])

In [84]:
x+y

array([[ 3,  5,  9],
       [ 5,  8, 10]])

In [85]:
x*y

array([[ 2,  6, 18],
       [ 4, 15, 24]])