In [1]:
import numpy as np

In [2]:
#The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. 


In [3]:
#One-Dimensional Array



#a = [a1, a2, a3]
#b = [b1, b2, b3]


#c = a + b
#c = [a1 + b1, a2 + b2, a3 + b3]

In [3]:
a = np.array([1, 2, 3])
#b = 2
#c = a + b
b=np.array([2,3,4])
c=a+b
c

array([3, 5, 7])

In [13]:
#Two-Dimensional Array

#A =[(a11, a12, a13),(a21, a22, a23)]
#B= [(b11, b12, b13),(b21, b22, b23)]

#C = A + B

#C= [(a11 + b11, a12 + b12, a13 + b13),(a21 + b21, a22 + b22, a23 + b23)]


In [8]:
A = np.array([[1, 2, 3], [4, 6, 7]])
#B=2
#C=A+B
#B=np.array([1,2,3])
B=np.array([(1,1,1),(2,2,2)])
A+B
#C

array([[2, 3, 4],
       [6, 8, 9]])

In [9]:
#Advanced Indexing

x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
y #(0,0), (1,1) and (2,0)


array([1, 4, 5])

In [10]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
#row indices of selection are [0, 0] and [3,3] whereas the column indices are [0,2] and [0,2].
y

array([[ 0,  2],
       [ 9, 11]])

In [13]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
# slicing 
z = x[1:4,1:3] 
# using advanced index for column 
y = x[1:4,[1,2]] 
y

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [27]:
#Boolean Array Indexing

x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]])

x[x > 5]

array([ 6,  7,  8,  9, 10, 11])

In [14]:
# NaN (Not a Number) elements are omitted by using ~ (complement operator).

a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])

In [29]:
#Maths with NumPy arrays


a = np.arange(1,6)
b = np.arange(6,11)




In [30]:
print('Subtract :',a-5)
print('Multiply :',a*5)
print('Divide :',a/5)
print('Power :',a**2)
print('Remainder :',a%5)

Subtract : [-4 -3 -2 -1  0]
Multiply : [ 5 10 15 20 25]
Divide : [0.2 0.4 0.6 0.8 1. ]
Power : [ 1  4  9 16 25]
Remainder : [1 2 3 4 0]


In [31]:
a = np.arange(5,15,2)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

Mean : 9.0
Standard deviation : 2.8284271247461903
Median : 9.0


In [32]:
a = np.array([[1,6],
[4,3]])
# minimum along a column
print('Min :',np.min(a,axis=0))
# maximum along a row
print('Max :',np.max(a,axis=1))

Min : [1 3]
Max : [6 4]


In [17]:
#Iterating Over Array

a = np.arange(0,60,5).reshape(3,4)
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [34]:
#numpy.nditer. It is an efficient multidimensional iterator object using
#which it is possible to iterate over an array.
for x in np.nditer(a):
   print(x,end=" ")

0 5 10 15 20 25 30 35 40 45 50 55 

In [18]:
#Transpose of the original array
a.T

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])