In [1]:
import numpy as np

In [3]:
#Random numbers in ndarrays
np.random.rand(3,3)

array([[0.22041136, 0.13347199, 0.23449691],
       [0.85245117, 0.68686694, 0.7856846 ],
       [0.90519359, 0.9867349 , 0.96881902]])

In [9]:
#An array of your choice
# create an array filled with any given value using the np.full() method.
np.full((2,3),6)

array([[6, 6, 6],
       [6, 6, 6]])

In [4]:
#Imatrix in NumPy
#np.eye() that returns an array with 1s along its diagonal and 0s everywhere else.
#Note: A square matrix has an N x N shape. This means it has the same number of rows and columns.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [6]:
# np.linspace(), but instead of step size, it takes in the number of samples that need to be retrieved from the interval. 
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [9]:
#Reshaping a NumPy array
a = np.array([3,6,9,12])
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

In [15]:
a = np.array([3,6,9,12,18,24])

In [20]:
#a.reshape(2,3)
a.reshape(3,2)

array([[ 3,  6],
       [ 9, 12],
       [18, 24]])

In [33]:
arr=np.array([(1,2,3),(4,5,6)])


In [34]:
#Flattening a NumPy array
#when you have a multidimensional array and want to collapse it to a single-dimensional 
#new ndarray is created in memory and flatten() is now pointing to this memory location.
arr.flatten()

#ravel() is pointing to the same memory location
#a=arr.ravel()


array([1, 2, 3, 4, 5, 6])

In [35]:
#Transpose of a NumPy array
#transpose() method.
#It takes the input array and swaps the rows with the column values, 
#and the column values with the values of the rows:


arr2=np.array([(1,2,3),(4,5,6)])
arr3=np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])


In [38]:
np.transpose(arr2)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [39]:
np.transpose(arr3)

array([[[ 1,  6],
        [ 4,  9]],

       [[ 2,  7],
        [ 5, 10]],

       [[ 3,  8],
        [ 6, 11]]])

In [40]:
#You can add a new axis to an array using the expand_dims() method 

a = np.array([1,2,3])
b = np.expand_dims(a,axis=0)
c = np.expand_dims(a,axis=1)


In [48]:
np.squeeze(c,axis=1)

array([1, 2, 3])

In [49]:
#Indexing and Slicing of NumPy array

#1D array
#arr_name[start:end:steps]
arr1=np.array([12,34,56,78,90,6,9,21])

In [50]:
arr1[1:8:2]

array([34, 78,  6, 21])

In [51]:
#Slicing 2-D NumPy arrays

arr2=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [52]:
#arr_name[row,col]
#arr_name[start:end:steps,start:end:steps]
arr2[1:,:2]

array([[4, 5],
       [7, 8]])

In [53]:
#Slicing 3-D NumPy arrays

arr3 = np.array([[[1,2],[3,4],[5,6]],# first axis array
[[7,8],[9,10],[11,12]],# second axis array
[[13,14],[15,16],[17,18]]])# third axis array

arr3


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [57]:
#arr_name[1st,2nd,3rd]
#arr_name[start:end:steps,start:end:steps,start:end:steps]
arr3[1:,0:,:]

array([[[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])