In [1]:
import numpy as np

In [2]:
# reshape
a = np.array([3,6,9,12])
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

In [5]:
#While reshaping, if you are unsure about the shape of any of the axis, 
#just input -1. NumPy automatically calculates the shape when it sees a -1:

a = np.array([3,6,9,12,18,24])
print('Three rows :','\n',np.reshape(a,(3,-1)))
print('Three columns :','\n',np.reshape(a,(-1,3)))

Three rows : 
 [[ 3  6]
 [ 9 12]
 [18 24]]
Three columns : 
 [[ 3  6  9]
 [12 18 24]]


In [13]:
#Flattening a NumPy array

a = np.ones((3,3))
b = a.flatten()
c = a.ravel()

#any changes made to the array returned from ravel() will also be reflected
#in the original array while this will not be the case with flatten().

In [6]:
#Transpose of a NumPy array
a = np.array([[1,2,3],[4,5,6]])
b = np.transpose(a)

In [7]:
#Expanding and Squeezing a NumPy array

# expand dimensions
a = np.array([1,2,3])
b = np.expand_dims(a,axis=0)
c = np.expand_dims(a,axis=1)

c.shape

(3, 1)

In [8]:
#Squeezing a NumPy array
#cannot select an axis to squeeze out which has size not equal to one

a = np.array([[[1,2,3],[4,5,6]]])
b = np.squeeze(a, axis=0)

In [17]:
#flip() method to reverse an ndarray.

a = np.array([[1,2,3],[6,7,8],[11,12,13]])

print(a)
#np.flip(a,axis=1)
np.flip(a,axis=0)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


array([[11, 12, 13],
       [ 6,  7,  8],
       [ 1,  2,  3]])

In [21]:
#Stacking and Concatenating NumPy arrays

#You can create a new array by combining existing arrays.
#Either combine the arrays vertically (i.e. along the rows) using the vstack() method,
#thereby increasing the number of rows in the resulting array


#Note : array should have the same size otherwise you are bound to get an error!


a = np.arange(0,5)
b = np.arange(5,10)


np.vstack((a,b))


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
#combine the arrays in a horizontal fashion (i.e. along the columns) using the hstack(),
#thereby increasing the number of columns in the resultant array


np.hstack((a,b))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#to combine arrays is using the dstack() method. 
#It combines array elements index by index and stacks them along the depth axis:
 
a = [[1,2],[3,4]]
b = [[5,6],[7,8]]
c = np.dstack((a,b))    


c


array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [27]:
#Concatenating ndarrays

a = np.arange(0,5).reshape(1,5)
b = np.arange(5,10).reshape(1,5)


#np.concatenate((a,b),axis=0)
#np.concatenate((a,b),axis=1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [29]:
#Another very useful function is the append method that adds new elements to the end of a ndarray.
#This is obviously useful when you already have an existing ndarray but want to add new values to it.


# append values to ndarray
a = np.array([[1,2],
             [3,4]])

np.append(a,[[5,6],[7,8]], axis=1)



array([[1, 2, 5, 6],
       [3, 4, 7, 8]])